/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.itson.catrina.ui;
import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import mx.itson.catrina.entidades.Cuenta;
import mx.itson.catrina.entidades.*;
import mx.itson.catrina.enumerador.Tipo;
/**
 *
 * @author julio
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }
    Cuenta cuenta;
    double total = 0;
    int mesAnterior = 1;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnMeses = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblRfc = new javax.swing.JLabel();
        lblDomicilio = new javax.swing.JLabel();
        lblCiudad = new javax.swing.JLabel();
        lblCp = new javax.swing.JLabel();
        lblCuenta = new javax.swing.JLabel();
        lblNumeroCuenta = new javax.swing.JLabel();
        lblClabe = new javax.swing.JLabel();
        lblMoneda = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMovimientos = new javax.swing.JTable();
        lblInicial = new javax.swing.JLabel();
        lblDepositos = new javax.swing.JLabel();
        lblRetiros = new javax.swing.JLabel();
        lblFinal = new javax.swing.JLabel();
        lblFinalPeriodo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBuscar.setText("Buscar...");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccione el origen de archivo:");

        btnMeses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        btnMeses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMesesActionPerformed(evt);
            }
        });

        jLabel2.setText("Seleccione el mes:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setText("ESTADO DE CUENTA:");

        lblNombre.setText("Nombre del cliente:");

        lblRfc.setText("RFC");

        lblDomicilio.setText("Domicilio");

        lblCiudad.setText("Ciudad");

        lblCp.setText("Código postal");

        lblCuenta.setText("Cuenta contable");

        lblNumeroCuenta.setText("Número de cuenta");

        lblClabe.setText("Clabe");

        lblMoneda.setText("Moneda");

        tblMovimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "FECHA", "DESCRIPCIÓN", "DEPÓSITO", "RETIRO", "SUBTOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMovimientos);
        if (tblMovimientos.getColumnModel().getColumnCount() > 0) {
            tblMovimientos.getColumnModel().getColumn(0).setResizable(false);
            tblMovimientos.getColumnModel().getColumn(1).setResizable(false);
            tblMovimientos.getColumnModel().getColumn(2).setResizable(false);
            tblMovimientos.getColumnModel().getColumn(4).setResizable(false);
        }

        lblInicial.setText("Saldo inicial");

        lblDepositos.setText("Depósitos");

        lblRetiros.setText("Retiros");

        lblFinal.setText("Saldo final");

        lblFinalPeriodo.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblFinalPeriodo.setText("Saldo al final del periodo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(159, 159, 159)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                                .addComponent(btnBuscar)))
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblRfc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNumeroCuenta))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCuenta))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCp)
                                    .addComponent(lblCiudad)
                                    .addComponent(lblDomicilio))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMoneda, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblClabe, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRetiros)
                            .addComponent(lblDepositos)
                            .addComponent(lblInicial)
                            .addComponent(lblFinal))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblFinalPeriodo)
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar)
                    .addComponent(jLabel3)
                    .addComponent(btnMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblCuenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRfc)
                    .addComponent(lblNumeroCuenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDomicilio)
                    .addComponent(lblClabe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCiudad)
                    .addComponent(lblMoneda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCp)
                .addGap(31, 31, 31)
                .addComponent(lblInicial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDepositos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRetiros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFinal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(lblFinalPeriodo)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Método con el botón buscar para deserializar el JSON.
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

                try {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));

            if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                File archivo = fileChooser.getSelectedFile();

                byte archivoBytes[] = Files.readAllBytes(archivo.toPath());
                String contenido = new String(archivoBytes, StandardCharsets.UTF_8);

                cuenta = new Cuenta().deserializar(contenido);

                lblNombre.setText(cuenta.getCliente().getNombre());
                lblRfc.setText("RFC: " + cuenta.getCliente().getRfc());
                lblDomicilio.setText("Domicilio: " + cuenta.getCliente().getDomicilio());
                lblCiudad.setText("Ciudad: " + cuenta.getCliente().getCiudad());
                lblCp.setText("Código postal: " + cuenta.getCliente().getCp());

                lblCuenta.setText(cuenta.getProducto());
                lblNumeroCuenta.setText("Cuenta: " + cuenta.getCuenta());
                lblClabe.setText("Clabe: " + cuenta.getClabe());
                lblMoneda.setText("Tipo de moneda: " + cuenta.getMoneda());

                DefaultTableModel movimientoModel = (DefaultTableModel) tblMovimientos.getModel();
                movimientoModel.setRowCount(0);
                int mesSeleccionado = 0;
                switch (btnMeses.getSelectedItem().toString()) {
                    case "Enero":
                        mesSeleccionado = 1;
                        break;
                    case "Febrero":
                        mesSeleccionado = 2;
                        break;
                    case "Marzo":
                        mesSeleccionado = 3;
                        break;
                    case "Abril":
                        mesSeleccionado = 4;
                        break;
                    case "Mayo":
                        mesSeleccionado = 5;
                        break;
                    case "Junio":
                        mesSeleccionado = 6;
                        break;
                    case "Julio":
                        mesSeleccionado = 7;
                        break;
                    case "Agosto":
                        mesSeleccionado = 8;
                        break;
                    case "Septiembre":
                        mesSeleccionado = 9;
                        break;
                    case "Octubre":
                        mesSeleccionado = 10;
                        break;
                    case "Noviembre":
                        mesSeleccionado = 11;
                        break;
                    case "Diciembre":
                        mesSeleccionado = 12;
                        break;
                }

                for (Movimiento m : cuenta.getMovimientos()) {
                    SimpleDateFormat fechaFormato = new SimpleDateFormat("dd/MM/yyyy");
                    // Determinar el mes del movimiento. Devuelve 1 - Enero, 2 - Febrero...12 - Diciembre.
                    String fecha = fechaFormato.format(m.getFecha());
                    LocalDate localDate = m.getFecha().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                    int mes = localDate.getMonthValue();

                    if (mes == mesSeleccionado) {
                        if (m.getTipo() == Tipo.DEPOSITO) {
                            double deposito = m.getCantidad();
                            total += m.getCantidad();
                            movimientoModel.addRow(new Object[]{(fecha), m.getDescripcion(), deposito, (null), (total)});

                        } else {
                            double retiro = m.getCantidad();
                            total -= m.getCantidad();
                            movimientoModel.addRow(new Object[]{(fecha), m.getDescripcion(), (null), retiro, (total)});

                        }
                    }

                }
                lblFinal.setText("Saldo final: " + total);
                lblFinalPeriodo.setText("Saldo final del periodo: " + total);
            }
        } catch (Exception ex) {
            System.err.print("Ocurrió un error: " + ex);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    //Botón con el método para cambiar los meses.
    private void btnMesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMesesActionPerformed

        DefaultTableModel movimientoModel = (DefaultTableModel) tblMovimientos.getModel();
        movimientoModel.setRowCount(0);

        int mesSeleccionado = 0;
        switch (btnMeses.getSelectedItem().toString()) {
            case "Enero":
                mesSeleccionado = 1;
                break;
            case "Febrero":
                mesSeleccionado = 2;
                break;
            case "Marzo":
                mesSeleccionado = 3;
                break;
            case "Abril":
                mesSeleccionado = 4;
                break;
            case "Mayo":
                mesSeleccionado = 5;
                break;
            case "Junio":
                mesSeleccionado = 6;
                break;
            case "Julio":
                mesSeleccionado = 7;
                break;
            case "Agosto":
                mesSeleccionado = 8;
                break;
            case "Septiembre":
                mesSeleccionado = 9;
                break;
            case "Octubre":
                mesSeleccionado = 10;
                break;
            case "Noviembre":
                mesSeleccionado = 11;
                break;
            case "Diciembre":
                mesSeleccionado = 12;
                break;
        }
        System.out.println(mesSeleccionado);
        System.out.println(mesAnterior);

        mesAnterior = mesSeleccionado;

        double depositos = 0;
        double retiros = 0;
        double saldoInicial = 0;
        for (Movimiento m : cuenta.getMovimientos()) {

            LocalDate localDate = m.getFecha().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            int mes = localDate.getMonthValue();

            Tipo tipo = m.getTipo();
            if (mes <= mesSeleccionado) {
                if (tipo == Tipo.DEPOSITO) {
                    total += m.getCantidad();
                } else {
                    total -= m.getCantidad();
                }
            }

            if (mes < mesSeleccionado) {
                if (tipo == Tipo.DEPOSITO) {
                    saldoInicial += m.getCantidad();
                } else {
                    saldoInicial -= m.getCantidad();
                }
            }

        }

        lblInicial.setText("Saldo inicial " + String.format("%,.2f", saldoInicial));

        double totalLocal = saldoInicial;

        //Tabla
        for (Movimiento m : cuenta.getMovimientos()) {
            SimpleDateFormat fechaFormato = new SimpleDateFormat("dd/MM/yyyy");
            String fecha = fechaFormato.format(m.getFecha());

            // Determinar el mes del movimiento. Devuelve 1 - Enero, 2 - Febrero...12 - Diciembre.
            LocalDate localDate = m.getFecha().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            int mes = localDate.getMonthValue();

            if (mes == mesSeleccionado) {
                if (m.getTipo() == Tipo.DEPOSITO) {
                    double deposito = m.getCantidad();
                    depositos += m.getCantidad();
                    totalLocal += deposito;
                    movimientoModel.addRow(new Object[]{(fecha), m.getDescripcion(), deposito, (null), String.format("%,.2f", totalLocal)});

                } else {
                    double retiro = m.getCantidad();
                    retiros += m.getCantidad();
                    totalLocal -= retiro;

                    movimientoModel.addRow(new Object[]{(fecha), m.getDescripcion(), (null), retiro, String.format("%,.2f", totalLocal)});
                }
            }
        }
        lblDepositos.setText("Depositos " + String.format("%,.2f", depositos));
        lblRetiros.setText("Retiros " + String.format("%,.2f", retiros));
        lblFinal.setText("Saldo final :" + String.format("%,.2f", total));
        lblFinalPeriodo.setText("Saldo final del periodo: " + String.format("%,.2f", total));
        total = 0;
    }//GEN-LAST:event_btnMesesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> btnMeses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCiudad;
    private javax.swing.JLabel lblClabe;
    private javax.swing.JLabel lblCp;
    private javax.swing.JLabel lblCuenta;
    private javax.swing.JLabel lblDepositos;
    private javax.swing.JLabel lblDomicilio;
    private javax.swing.JLabel lblFinal;
    private javax.swing.JLabel lblFinalPeriodo;
    private javax.swing.JLabel lblInicial;
    private javax.swing.JLabel lblMoneda;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumeroCuenta;
    private javax.swing.JLabel lblRetiros;
    private javax.swing.JLabel lblRfc;
    private javax.swing.JTable tblMovimientos;
    // End of variables declaration//GEN-END:variables
}
